"""
IDA batch script: Analyze Sonic 1 ROM with MC68000 processor and export full disassembly.
Run via: idat64.exe -A -S"batch_analyze.py" -p68K -o"sonic1.i64" "path/to/rom.gen"
"""
import ida_auto
import ida_bytes
import ida_funcs
import ida_ida
import ida_idaapi
import ida_loader
import ida_segment
import ida_name
import ida_lines
import ida_nalt
import idautils
import idc
import os

OUTPUT_FILE = os.path.join(os.path.dirname(ida_nalt.get_input_file_path()), "sonic1_disasm.asm")

def wait_for_analysis():
    """Wait for IDA auto-analysis to complete."""
    ida_auto.auto_wait()

def define_vector_table():
    """Define the M68K exception vector table at 0x0-0xFF."""
    vector_names = [
        "InitialSSP", "ResetPC", "BusError", "AddressError",
        "IllegalInstr", "ZeroDivide", "CHKInstr", "TRAPVInstr",
        "PrivilegeViol", "Trace", "LineA", "LineF",
        "Reserved0C", "Reserved0D", "Reserved0E", "UninitIntVec",
        "Reserved10", "Reserved11", "Reserved12", "Reserved13",
        "Reserved14", "Reserved15", "Reserved16", "Reserved17",
        "SpuriousInt", "IRQ1", "ExtInt", "IRQ3",
        "HBlankInt", "IRQ5", "VBlankInt", "IRQ7",
    ]
    # TRAP vectors 0x80-0xBF (TRAP #0 - #15)
    for i in range(16):
        vector_names.append(f"Trap{i}")
    # Remaining reserved up to 0xFF
    while len(vector_names) < 64:
        vector_names.append(f"Reserved{len(vector_names):02X}")
    
    for i, name in enumerate(vector_names):
        addr = i * 4
        # Make the vector a 32-bit value
        idc.del_items(addr, 0, 4)
        idc.create_dword(addr)
        idc.set_name(addr, f"Vec_{name}", idc.SN_NOCHECK)
        
        # For code vectors (not SSP), try to create functions at the target
        if i >= 1:  # Skip initial SSP
            target = idc.get_wide_dword(addr)
            if 0x200 <= target < 0x80000:
                idc.add_func(target)

def create_entry_points():
    """Create additional known entry points."""
    # Reset vector (entry point)
    entry = idc.get_wide_dword(4)
    if entry:
        idc.add_entry(entry, entry, "start", 1)

def export_disassembly():
    """Export full disassembly listing."""
    print(f"Exporting disassembly to: {OUTPUT_FILE}")
    
    lines = []
    lines.append("; Sonic The Hedgehog (USA, Europe) - Full Disassembly")
    lines.append("; Processor: Motorola 68000")
    lines.append("; Generated by IDA Pro")
    lines.append(";")
    lines.append("")
    
    # Header info
    lines.append("; === ROM HEADER (0x100-0x1FF) ===")
    lines.append("")
    
    # Export all segments
    for seg_ea in idautils.Segments():
        seg = ida_segment.getseg(seg_ea)
        seg_name = ida_segment.get_segm_name(seg)
        lines.append(f"; ========== Segment: {seg_name} (0x{seg.start_ea:X} - 0x{seg.end_ea:X}) ==========")
        lines.append("")
        
        ea = seg.start_ea
        while ea < seg.end_ea and ea != ida_idaapi.BADADDR:
            # Get all comment and label lines
            func = ida_funcs.get_func(ea)
            
            # Function header
            if func and func.start_ea == ea:
                fname = ida_funcs.get_func_name(func.start_ea)
                lines.append("")
                lines.append(f"; =============== F U N C T I O N ===============")
                lines.append(f"; {fname}")
                lines.append("")
            
            # Name/label
            name = ida_name.get_name(ea)
            if name:
                lines.append(f"{name}:")
            
            # Get the disassembly line
            disasm = idc.generate_disasm_line(ea, 0)
            if disasm:
                lines.append(f"  {ea:08X}  {disasm}")
            
            # Next item
            next_ea = idc.next_head(ea, seg.end_ea)
            if next_ea == ida_idaapi.BADADDR or next_ea <= ea:
                break
            ea = next_ea
    
    # Count functions
    func_count = sum(1 for _ in idautils.Functions())
    lines.append("")
    lines.append(f"; Total functions: {func_count}")
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"Disassembly exported: {len(lines)} lines, {func_count} functions")

def main():
    print("=== Sonic 1 ROM Analysis ===")
    print(f"Processor: {ida_ida.inf_get_procname()}")
    print(f"Input: {ida_nalt.get_input_file_path()}")
    
    # Wait for initial auto-analysis
    wait_for_analysis()
    
    # Define vector table and create functions
    define_vector_table()
    
    # Create entry points
    create_entry_points()
    
    # Re-run auto-analysis after defining vectors
    ida_auto.auto_wait()
    
    # Export disassembly
    export_disassembly()
    
    print("=== Done ===")
    
    # Exit IDA in batch mode
    idc.qexit(0)

if __name__ == "__main__":
    main()
else:
    main()
